-- Tabelas para Análise de Produtividade

create table if not exists productivity_settings (
  id bigint generated by default as identity primary key,
  action_type text not null,
  points integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint productivity_settings_action_type_unique unique (action_type)
);

create table if not exists productivity_daily (
  id bigint generated by default as identity primary key,
  date date not null,
  collaborator_id text,
  collaborator_name text not null,
  points_total integer not null default 0,
  checklist_points integer not null default 0,
  comment_points integer not null default 0,
  ai_summary text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists productivity_activities (
  id bigint generated by default as identity primary key,
  date date not null,
  collaborator_id text,
  collaborator_name text not null,
  type text not null check (type in ('comment', 'checklist')),
  card_name text,
  item_name text,
  content text,
  points integer not null default 0,
  ai_reason text,
  created_at timestamptz not null default now()
);

create index if not exists idx_productivity_daily_date on productivity_daily(date);
create index if not exists idx_productivity_daily_collaborator on productivity_daily(collaborator_id);
create index if not exists idx_productivity_activities_date on productivity_activities(date);
create index if not exists idx_productivity_activities_collaborator on productivity_activities(collaborator_id);
create index if not exists idx_productivity_activities_points on productivity_activities(points desc);

create or replace function set_updated_at_timestamp()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists trg_productivity_daily_updated_at on productivity_daily;
create trigger trg_productivity_daily_updated_at
before update on productivity_daily
for each row execute function set_updated_at_timestamp();

drop trigger if exists trg_productivity_settings_updated_at on productivity_settings;
create trigger trg_productivity_settings_updated_at
before update on productivity_settings
for each row execute function set_updated_at_timestamp();
